export const siteConfig = {
  name: "BS. Trần Huyền Trang",
  title: "BS. Trần Huyền Trang — Chuyên gia Tĩnh mạch & Tim mạch",
  description:
    "Chuyên sâu về bệnh lý tim và mạch máu. Tư vấn 1:1 miễn phí tại PK ABClinic 159B Lê Thanh Nghị, Hà Nội.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://bshuyentrang.vercel.app",
  phone: "0919911593",
  phoneDisplay: "091 991 1593",
  email: "trangkien07@gmail.com",
  address: "PK ABClinic — 159B Lê Thanh Nghị",
  addressFull: "159B Lê Thanh Nghị, Hà Nội",
  hours: "17h các ngày trong tuần · 14–17h chiều thứ 7 tại ABClinic",
  cvPdfUrl: "/pdf/bs_huyentrang.pdf",
  cvPageUrl: "/ly-lich",
  locale: "vi_VN",
  keywords: [
    "BS Trần Huyền Trang",
    "tĩnh mạch",
    "tim mạch",
    "suy giãn tĩnh mạch",
    "ABClinic",
    "Hà Nội",
    "can thiệp nội mạch",
  ],
} as const;
